"""assessment org_name and logo_url (A12 branding)

Revision ID: 0ae2d36aff72
Revises: ad5e81ec2b2b
Create Date: 2026-07-26 10:34:37.170171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0ae2d36aff72'
down_revision: Union[str, Sequence[str], None] = 'ad5e81ec2b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Per-assessment branding (A12): optional org_name + logo_url (a URL
    reference, never base64) shown on the candidate IDE header. Both nullable —
    additive, existing assessments render unbranded."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.drop_column('logo_url')
        batch_op.drop_column('org_name')

    # ### end Alembic commands ###
