"""assessment and assessment_question; invite.assessment_id

Revision ID: 15556d728532
Revises: f21c8592dee0
Create Date: 2026-07-23 16:24:25.467284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '15556d728532'
down_revision: Union[str, Sequence[str], None] = 'f21c8592dee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add the first-class Assessment (T4): an ordered, reusable set of questions.

    New `assessment` (owns the per-assessment total `duration_minutes`) and
    `assessmentquestion` (membership + position) tables. `invite.question_id`
    becomes nullable and a nullable `invite.assessment_id` is added — an invite now
    points at EITHER a legacy single question or an assessment. Additive: existing
    single-question invites keep their question_id and are untouched.
    """
    op.create_table('assessment',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['interviewer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_status'), ['status'], unique=False)

    op.create_table('assessmentquestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'question_id', name='uq_assessment_question')
    )
    with op.batch_alter_table('assessmentquestion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessmentquestion_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessmentquestion_question_id'), ['question_id'], unique=False)

    with op.batch_alter_table('invite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assessment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.alter_column('question_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_invite_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_invite_assessment_id', 'assessment', ['assessment_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite', schema=None) as batch_op:
        batch_op.drop_constraint('fk_invite_assessment_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_invite_assessment_id'))
        batch_op.alter_column('question_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('assessment_id')

    with op.batch_alter_table('assessmentquestion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessmentquestion_question_id'))
        batch_op.drop_index(batch_op.f('ix_assessmentquestion_assessment_id'))

    op.drop_table('assessmentquestion')
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_status'))
        batch_op.drop_index(batch_op.f('ix_assessment_owner_id'))

    op.drop_table('assessment')
    # ### end Alembic commands ###
