"""candidate_attempt.candidate_name (A10 identity anchor)

Revision ID: 4185e1964c38
Revises: 0ae2d36aff72
Create Date: 2026-07-26 10:59:13.769355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4185e1964c38'
down_revision: Union[str, Sequence[str], None] = '0ae2d36aff72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Anchor candidate identity (A10): candidate_name is stamped once at the
    first /start (alongside started_at) and reused for every submission in the
    sitting, instead of trusting the name resent on each individual /submit.
    Nullable so a pre-existing attempt row degrades gracefully."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidateattempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candidate_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidateattempt', schema=None) as batch_op:
        batch_op.drop_column('candidate_name')

    # ### end Alembic commands ###
