"""submission unique per invite candidate question

Revision ID: ad5e81ec2b2b
Revises: 15556d728532
Create Date: 2026-07-23 16:44:03.779011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ad5e81ec2b2b'
down_revision: Union[str, Sequence[str], None] = '15556d728532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """One candidate attempt per (invite, candidate, QUESTION) — T4.

    An assessment invite carries several questions, so the one-attempt rule gains
    `question_id`. Safe on existing data: every row already has a question_id, and
    the new key is a superset of the old, so no previously-valid row conflicts. For
    a legacy single-question invite the added column is constant, so the rule is
    unchanged in practice.
    """
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_submission_invite_candidate'), type_='unique')
        batch_op.create_unique_constraint('uq_submission_invite_candidate_question', ['invite_id', 'candidate_email', 'question_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_constraint('uq_submission_invite_candidate_question', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_submission_invite_candidate'), ['invite_id', 'candidate_email'])

    # ### end Alembic commands ###
