"""initial schema

Revision ID: cae37faa2bff
Revises: 
Create Date: 2026-07-14 23:24:11.625597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cae37faa2bff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviewer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interviewer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interviewer_email'), ['email'], unique=True)

    op.create_table('question',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('constraints', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('time_limit_s', sa.Float(), nullable=False),
    sa.Column('pass_threshold', sa.Float(), nullable=False),
    sa.Column('required_complexity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('example_input', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('example_output', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['interviewer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_owner_id'), ['owner_id'], unique=False)

    op.create_table('invite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('recipients', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['interviewer.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invite_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_invite_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invite_token'), ['token'], unique=True)

    op.create_table('questiontestcase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stdin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expected', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questiontestcase', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questiontestcase_question_id'), ['question_id'], unique=False)

    op.create_table('submission',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invite_id', sa.Integer(), nullable=True),
    sa.Column('candidate', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('candidate_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invite_id'], ['invite.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submission_agent_job_id'), ['agent_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submission_invite_id'), ['invite_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submission_question_id'), ['question_id'], unique=False)

    op.create_table('assessmentresult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verdict', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score_pct', sa.Float(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_result', sa.JSON(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessmentresult', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessmentresult_submission_id'), ['submission_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessmentresult', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessmentresult_submission_id'))

    op.drop_table('assessmentresult')
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submission_question_id'))
        batch_op.drop_index(batch_op.f('ix_submission_invite_id'))
        batch_op.drop_index(batch_op.f('ix_submission_agent_job_id'))

    op.drop_table('submission')
    with op.batch_alter_table('questiontestcase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questiontestcase_question_id'))

    op.drop_table('questiontestcase')
    with op.batch_alter_table('invite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invite_token'))
        batch_op.drop_index(batch_op.f('ix_invite_question_id'))
        batch_op.drop_index(batch_op.f('ix_invite_created_by'))

    op.drop_table('invite')
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_owner_id'))

    op.drop_table('question')
    with op.batch_alter_table('interviewer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interviewer_email'))

    op.drop_table('interviewer')
    # ### end Alembic commands ###
