"""question duration_minutes and candidate_attempt

Revision ID: f21c8592dee0
Revises: 3c8072a71f16
Create Date: 2026-07-22 21:23:51.578816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f21c8592dee0'
down_revision: Union[str, Sequence[str], None] = '3c8072a71f16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add the assessment timer: question.duration_minutes + candidateattempt.

    duration_minutes is nullable (None = untimed), so existing questions stay
    untimed. candidateattempt records the server-authoritative clock start per
    (invite, candidate_email), unique so a re-open can't reset the deadline.
    """
    op.create_table('candidateattempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invite_id', sa.Integer(), nullable=False),
    sa.Column('candidate_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invite_id'], ['invite.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_id', 'candidate_email', name='uq_attempt_invite_candidate')
    )
    with op.batch_alter_table('candidateattempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidateattempt_candidate_email'), ['candidate_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidateattempt_invite_id'), ['invite_id'], unique=False)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_minutes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('duration_minutes')

    with op.batch_alter_table('candidateattempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidateattempt_invite_id'))
        batch_op.drop_index(batch_op.f('ix_candidateattempt_candidate_email'))

    op.drop_table('candidateattempt')
    # ### end Alembic commands ###
